export const free = {
  type: "Free",
  price: "0",
  text: "Wallet Protection for Crypto & NFT assets.",
  heading: "Free Includes:",
  btnText: "Try for free now",
  features: [
    "Wallet Monitoring",
    "Live notifications for important transactions",
    "SMS and e-mail alerts for inbound and outbound wallet activity",
    "Unlimited Wallets",
  ],
};
export const yearlyStandard = {
  type: "Standard",
  planType: "year",
  text: "Wallet Protection, Inheritance Planning & Password Management for Crypto & NFT assets",
  textTwo: "Everything in Free Plan, plus",
  heading: "What’s Included:",
  price: "199",
  features: [
    "Single key self-custody security",
    "Legacy Lifeline (Emergency Backup Wallet)",
    "Create Smart Contract Crypto & NFT Will™",
    "Create Exchange Will",
    "Set Crypto Price Alerts",
    "LegacyPass Blockchain Password Manager",
  ],
};
export const yearlyPremium = {
  type: "Premium",
  price: "299",
  text: "Wallet Protection, Inheritance Planning & Password Management for All Assets",
  textTwo: "Everything in Standard, plus",
  planType: "year",
  heading: "Premium Includes:",
  features: [
    "Create Traditional Will",
    "Asset Aggregation- Assets & Liabilities",
    "Subscription Manager",
    "Financial Reports - Net Worth",
    "Create Revocable Living Trust Docs",
    "Create Health Care Directives",
    "Create Guardianship Directives",
    "Create Power of Attorney Documents",
    "Create Social Directives",
    "Legal Suite Vault (1GB)",
    "Manager and Sharing",
    "Beneficiary/Trusted Contact Reporting",
    "Future Messaging",
    "Legacy Journal",
    "Legal Document Vault (1GB)",
    "Digital Document Vault (5GB)",
  ],
  addOns: ["$2.99/month for additional 5G storage*"],
};
export const yearlyUltimate = {
  type: "Ultimate",
  btnText: "Notify Me",
  btnLink: "/contact",
  price: "1999",
  text: "Wallet Protection, Inheritance Planning, Password Management & Personalized Service for All Assets",
  textTwo: "Everything in Premium, plus",
  planType: "year",
  heading: "Ultimate Includes:",
  features: [
    "Onboarding package with Ledger Wallet included",
    "Premium Concierge Services",
    "24/7 emergency support",
    "2-of-3 multi-sig (or more)",
    "Personalized End of Life Planning",
    "Support Family (up to 4 Members)",
  ],
};

export const monthlyStandard = {
  type: "Standard",
  planType: "month",
  text: "Wallet Protection, Inheritance Planning & Password Management for Crypto & NFT assets",
  heading: "What’s Included:",
  textTwo: "Everything in Free Plan, plus",
  price: "19",
  features: [
    "Single key self-custody security",
    "Legacy Lifeline (Emergency Backup Wallet)",
    "Create Smart Contract Crypto & NFT Will™",
    "Create Exchange Will",
    "Set Crypto Price Alerts",
    "LegacyPass Blockchain Password Manager",
  ],
};

export const monthlyPremium = {
  type: "Premium",
  price: "29",
  planType: "month",
  heading: "Premium Includes:",
  textTwo: "Everything in Standard, plus",
  text: "Wallet Protection, Inheritance Planning & Password Management for All Assets",
  features: [
    "Create Traditional Will",
    "Asset Aggregation- Assets & Liabilities",
    "Subscription Manager",
    "Financial Reports - Net Worth",
    "Create Revocable Living Trust Docs",
    "Create Health Care Directives",
    "Create Guardianship Directives",
    "Create Power of Attorney Documents",
    "Create Social Directives",
    "Legal Suite Vault (1GB)",
    "Manager and Sharing",
    "Beneficiary/Trusted Contact Reporting",
    "Future Messaging",
    "Legacy Journal",
    "Legal Document Vault (1GB)",
    "Digital Document Vault (5GB)",
  ],
  addOns: ["$2.99/month for additional 5G storage*"],
};

export const monthlyUltimate = {
  type: "Ultimate",
  btnText: "Notify Me",
  btnLink: "/contact",
  price: "199",
  text: "Wallet Protection, Inheritance Planning, Password Management & Personalized Service for All Assets",
  planType: "month",
  textTwo: "Everything in Premium, plus",
  heading: "Ultimate Includes:",
  features: [
    "Onboarding package with Ledger Wallet included",
    "Premium Concierge Services",
    "24/7 emergency support",
    "2-of-3 multi-sig (or more)",
    "Personalized End of Life Planning",
    "Support Family (up to 4 Members)",
  ],
};
